### ISSUE TITLE
AttributeError: type object 'PageMeta' has no attribute '_deferred'

### ISSUE THREAD

**Issue by sitare** [pmaigutyak/mp-seo#1]
Hi, 

I do all the uploads, but I get an error when migrating.

> Installing collected packages: django-mp-seo, django-modeltranslation
>   Running setup.py install for django-mp-seo
>     
>   no previously-included directories found matching '*.pyc'
>   Running setup.py install for django-modeltranslation
>     
> Successfully installed django-mp-seo django-modeltranslation
> Cleaning up...

`./manage.py migrate`

----
AttributeError: type object 'PageMeta' has no attribute '_deferred'
----

**Comment by pmaigutyak** [comment]
Hello, 
Let me check!

**Comment by pmaigutyak** [comment]
Could you write me versions of your django and django-modeltranslation apps ?

**Comment by pmaigutyak** [comment]
The problem in django-modeltranslation app.
Please run:
pip django-modeltranslation==0.12.1

**Comment by sitare** [comment]
Thank you. Problem solved
